<?php

/**
 * Copyright © Klevu Oy. All rights reserved. See LICENSE.txt for license details.
 */

declare(strict_types=1);

namespace Klevu\PlatformPipelines\Service\Action;

use Klevu\PlatformPipelines\Api\GenerateConfigurationOverridesContentActionInterface;

/**
 * This is a default content generator which should be replaced within modules to provide specific overrides
 */
class GenerateConfigurationOverridesContent implements GenerateConfigurationOverridesContentActionInterface
{
    /**
     * @return string
     */
    public function execute(): string
    {
        return <<<'WARNING'
# WARNING: This file is autogenerated.
# Any changes will be reflected in the next applicable pipeline execution, without requiring recompilation
#   however, they will be lost when this file is regenerated
WARNING;
    }
}
